-- Direct forum replies + normal user notifications (separate from staff notifications).

alter table public.forum_posts
  add column if not exists reply_to_post_id bigint references public.forum_posts(id) on delete set null;

create index if not exists forum_posts_reply_to_idx
  on public.forum_posts(reply_to_post_id)
  where reply_to_post_id is not null;

create table if not exists public.forum_user_notifications(
  id bigint generated by default as identity primary key,
  recipient_user_id uuid not null references auth.users(id) on delete cascade,
  actor_user_id uuid references auth.users(id) on delete set null,
  kind text not null check (kind in ('reply','quote')),
  title text not null check (char_length(title) between 1 and 180),
  body text not null default '' check (char_length(body) <= 600),
  href text not null check (char_length(href) between 1 and 500),
  topic_id bigint references public.forum_topics(id) on delete cascade,
  post_id bigint references public.forum_posts(id) on delete cascade,
  source_post_id bigint references public.forum_posts(id) on delete set null,
  event_key text not null check (char_length(event_key) between 3 and 128),
  created_at timestamptz not null default now(),
  read_at timestamptz,
  unique(recipient_user_id,event_key)
);

alter table public.forum_user_notifications enable row level security;
revoke all on public.forum_user_notifications from public,anon,authenticated;
grant select on public.forum_user_notifications to authenticated;
grant update(read_at) on public.forum_user_notifications to authenticated;

drop policy if exists forum_user_notifications_select_own on public.forum_user_notifications;
create policy forum_user_notifications_select_own
on public.forum_user_notifications for select to authenticated
using (recipient_user_id=(select auth.uid()));

drop policy if exists forum_user_notifications_update_own on public.forum_user_notifications;
create policy forum_user_notifications_update_own
on public.forum_user_notifications for update to authenticated
using (recipient_user_id=(select auth.uid()))
with check (recipient_user_id=(select auth.uid()));

create index if not exists forum_user_notifications_recipient_created_idx
  on public.forum_user_notifications(recipient_user_id,created_at desc);
create index if not exists forum_user_notifications_unread_idx
  on public.forum_user_notifications(recipient_user_id,created_at desc)
  where read_at is null;

create or replace function private.forum_notify_direct_interactions()
returns trigger language plpgsql security definer set search_path=''
as $$
declare
  v_actor_name text;
  v_topic_title text;
  v_recipient uuid;
  v_quote_match text[];
  v_quote_post bigint;
begin
  select coalesce(p.username,p.display_name,'Usuario') into v_actor_name
  from public.profiles p where p.id=new.author_id;

  select t.title into v_topic_title
  from public.forum_topics t where t.id=new.topic_id;

  if new.reply_to_post_id is not null then
    select p.author_id into v_recipient
    from public.forum_posts p
    where p.id=new.reply_to_post_id
      and p.topic_id=new.topic_id
      and p.deleted_at is null
      and not p.is_hidden;

    if v_recipient is not null and v_recipient is distinct from new.author_id then
      insert into public.forum_user_notifications(
        recipient_user_id,actor_user_id,kind,title,body,href,
        topic_id,post_id,source_post_id,event_key
      ) values(
        v_recipient,new.author_id,'reply',
        left(coalesce(v_actor_name,'Usuario')||' te ha respondido',180),
        left('En «'||coalesce(v_topic_title,'un tema del foro')||'».',600),
        '/foro/?t='||new.topic_id||'#post-'||new.id,
        new.topic_id,new.id,new.reply_to_post_id,
        'reply:'||new.id||':'||new.reply_to_post_id
      )
      on conflict(recipient_user_id,event_key) do nothing;
    end if;
  end if;

  for v_quote_match in
    select regexp_matches(new.body,'\[quote="[^"]{1,80}" post="([0-9]+)"\]','g')
  loop
    begin
      v_quote_post:=v_quote_match[1]::bigint;
    exception when others then
      continue;
    end;

    if new.reply_to_post_id is not null and v_quote_post=new.reply_to_post_id then
      continue;
    end if;

    select p.author_id into v_recipient
    from public.forum_posts p
    where p.id=v_quote_post
      and p.topic_id=new.topic_id
      and p.deleted_at is null
      and not p.is_hidden;

    if v_recipient is not null and v_recipient is distinct from new.author_id then
      insert into public.forum_user_notifications(
        recipient_user_id,actor_user_id,kind,title,body,href,
        topic_id,post_id,source_post_id,event_key
      ) values(
        v_recipient,new.author_id,'quote',
        left(coalesce(v_actor_name,'Usuario')||' te ha citado',180),
        left('En «'||coalesce(v_topic_title,'un tema del foro')||'».',600),
        '/foro/?t='||new.topic_id||'#post-'||new.id,
        new.topic_id,new.id,v_quote_post,
        'quote:'||new.id||':'||v_recipient::text
      )
      on conflict(recipient_user_id,event_key) do nothing;
    end if;
  end loop;

  return new;
end;$$;

drop trigger if exists forum_user_notifications_post_insert on public.forum_posts;
create trigger forum_user_notifications_post_insert
after insert on public.forum_posts
for each row execute function private.forum_notify_direct_interactions();

drop function if exists public.forum_create_reply(bigint,text);

create function public.forum_create_reply(
  p_topic_id bigint,
  p_body text,
  p_reply_to_post_id bigint
)
returns bigint language plpgsql security invoker set search_path=''
as $$
declare
  v_user uuid:=auth.uid();
  v_post_id bigint;
  v_body text:=btrim(coalesce(p_body,''));
begin
  if v_user is null then raise exception 'authentication required'; end if;
  if char_length(v_body)<1 or char_length(v_body)>20000 or position(chr(0) in v_body)>0 then
    raise exception 'invalid body';
  end if;
  if exists(
    select 1 from public.forum_posts
    where author_id=v_user and created_at>now()-interval '4 seconds'
  ) then raise exception 'reply rate limit'; end if;

  if p_reply_to_post_id is not null and not exists(
    select 1 from public.forum_posts p
    where p.id=p_reply_to_post_id
      and p.topic_id=p_topic_id
      and p.deleted_at is null
      and not p.is_hidden
  ) then raise exception 'invalid reply target'; end if;

  insert into public.forum_posts(topic_id,author_id,body,reply_to_post_id)
  values(p_topic_id,v_user,v_body,p_reply_to_post_id)
  returning id into v_post_id;
  return v_post_id;
end;$$;

revoke all on function public.forum_create_reply(bigint,text,bigint) from public,anon;
grant execute on function public.forum_create_reply(bigint,text,bigint) to authenticated;
