-- A 90 Files private, first-party analytics.
-- No IP address, User-Agent or authenticated user ID is stored.

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  event_type text not null check (event_type in ('page_view','click','download')),
  path text not null,
  target text,
  referrer_host text,
  session_id uuid,
  is_entry boolean not null default false
);

alter table public.analytics_events enable row level security;

create index if not exists analytics_events_time_idx on public.analytics_events (occurred_at desc);
create index if not exists analytics_events_type_time_idx on public.analytics_events (event_type, occurred_at desc);

-- Policies in production:
-- analytics_insert_public: anon/authenticated can INSERT only validated event shapes.
-- analytics_select_super_admin: authenticated SELECT is limited to current_app_role() = super_admin.
-- analytics_dashboard(integer): SECURITY INVOKER aggregate RPC for the private dashboard.
